FROM ubuntu

RUN apt-get update

WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get install -y software-properties-common python3 python3-pip  python3-venv

COPY requirements.txt ./

RUN pip3 install --no-cache-dir -r requirements.txt

COPY lib lib
COPY web web
COPY tests tests

WORKDIR /usr/src/app/web/src

VOLUME /usr/src/app/web/src/sqlite3

CMD [ "./run.sh"]
