version: '2'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile-node
    restart: always
    #    ports:
    #      - 8545:8545
    volumes:
      - ./chaindata:/usr/src/app/node/chaindata
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    restart: always
    ports:
      - 4000:8000
    volumes:
      - ./storage:/usr/src/app/storage
      - ./chaindata:/usr/src/app/node/chaindata
      - ./sqllite:/usr/src/app/web/src/sqlite3
  ipfs:
    image: ipfs/go-ipfs
    restart: always
    environment:
      - IPFS_PROFILE=server
    ports:
      - 4001:4001
      - 127.0.0.1:8080:8080
      - 127.0.0.1:5001:5001
    volumes:
      - ./ipfs_data:/data/ipfs
