FROM ubuntu

RUN apt-get update

WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get install -y software-properties-common python3 python3-pip  python3-venv

RUN alias python=python3

RUN add-apt-repository -y ppa:ethereum/ethereum && \
    apt-get update && \
    apt-get install -y ethereum solc

COPY requirements.txt ./

RUN pip3 install --no-cache-dir -r requirements.txt

COPY lib lib
COPY node node
COPY tests tests

WORKDIR /usr/src/app/node

RUN echo "var promTokenOutput=`solc --optimize --combined-json abi,bin,interface ../lib/contract/PromToken.sol`" > promtoken.js

CMD geth --dev --datadir chaindata/ --minerthreads 1 --preload "init.js"
