version: '2'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile-node
    restart: always
    ports:
      - 4001:8545
    volumes:
      - ./chaindata:/usr/src/app/node/chaindata
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - 4000:8000
    volumes:
      - ./storage:/usr/src/app/storage
      - ./chaindata:/usr/src/app/node/chaindata
  ipfs:
    image: ipfs/go-ipfs
    environment:
      - IPFS_PROFILE=server
    ports:
      - 4002:4001
      - 127.0.0.1:8080:8080
      - 127.0.0.1:5001:5001
    volumes:
      - ./ipfs_data:/data/ipfs
